

// add to cart
export const ADD_ITEMS_TO_CART_REQUEST = "ADD_ITEMS_TO_CART_REQUEST"

export const ADD_ITEMS_TO_CART_SUCCESS = "ADD_ITEMS_TO_CART_SUCCESS"

export const ADD_ITEMS_TO_CART_FAIL = "ADD_ITEMS_TO_CART_FAIL"

// remove from cart
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"

export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"

export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL"


// quantity change in cart
export const CART_QUANTITY_CHANGE_REQUEST = "CART_QUANTITY_CHANGE_REQUEST"

export const CART_QUANTITY_CHANGE_SUCCESS = "CART_QUANTITY_CHANGE_SUCCESS"

export const CART_QUANTITY_CHANGE_FAIL = "CART_QUANTITY_CHANGE_FAIL"


// shipping address
export const SHIPPING_ADDRESS_ADD_REQUEST = "SHIPPING_ADDRESS_ADD_REQUEST"

export const SHIPPING_ADDRESS_ADD_SUCCESS = "SHIPPING_ADDRESS_ADD_SUCCESS"

export const SHIPPING_ADDRESS_ADD_FAIL = "SHIPPING_ADDRESS_ADD_FAIL"