
// create order
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"

export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"

export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"


// get orders
export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"

export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"

export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"


//  get single order preview
export const GET_ORDER_PREVIEW_REQUEST = "GET_ORDER_PREVIEW_REQUEST"

export const GET_ORDER_PREVIEW_SUCCESS = "GET_ORDER_PREVIEW_SUCCESS"

export const GET_ORDER_PREVIEW_FAIL = "GET_ORDER_PREVIEW_FAIL"


// get all orders -- admin
export const GET_ADMIN_ORDERS_REQUEST = "GET_ADMIN_ORDERS_REQUEST"

export const GET_ADMIN_ORDERS_SUCCESS = "GET_ADMIN_ORDERS_SUCCESS"

export const GET_ADMIN_ORDERS_FAIL = "GET_ADMIN_ORDERS_FAIL"

// delete order -- admin
export const DELETE_ADMIN_ORDER_REQUEST = "DELETE_ADMIN_ORDER_REQUEST"

export const DELETE_ADMIN_ORDER_SUCCESS = "DELETE_ADMIN_ORDER_SUCCESS"

export const DELETE_ADMIN_ORDER_FAIL = "DELETE_ADMIN_ORDER_FAIL"


//  get admin order preview  -- admin
export const GET_ADMIN_ORDER_PREVIEW_REQUEST = "GET_ADMIN_ORDER_PREVIEW_REQUEST"

export const GET_ADMIN_ORDER_PREVIEW_SUCCESS = "GET_ADMIN_ORDER_PREVIEW_SUCCESS"

export const GET_ADMIN_ORDER_PREVIEW_FAIL = "GET_ADMIN_ORDER_PREVIEW_FAIL"


//  admin order status change  -- admin
export const ADMIN_ORDER_STATUS_CHANGE_REQUEST = "ADMIN_ORDER_STATUS_CHANGE_REQUEST"

export const ADMIN_ORDER_STATUS_CHANGE_SUCCESS = "ADMIN_ORDER_STATUS_CHANGE_SUCCESS"

export const ADMIN_ORDER_STATUS_CHANGE_FAIL = "ADMIN_ORDER_STATUS_CHANGE_FAIL"


export const RESET_SUCCESS = "RESET_SUCCESS"


export const CLEAR_ERROR = "CLEAR_ERROR"