// all products
export const  PRODUCTS_GET_REQUEST = "PRODUCTS_GET_REQUEST"

export const  PRODUCTS_GET_SUCCESS = "PRODUCTS_GET_SUCCESS"

export const  PRODUCTS_GET_FAIL = "PRODUCTS_GET_FAIL"

// single products
export const  PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST"

export const  PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS"

export const  PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL"

// get all products -- admin
export const  ADMIN_PRODUCTS_GET_REQUEST = "ADMIN_PRODUCTS_GET_REQUEST"

export const  ADMIN_PRODUCTS_GET_SUCCESS = "ADMIN_PRODUCTS_GET_SUCCESS"

export const  ADMIN_PRODUCTS_GET_FAIL = "ADMIN_PRODUCTS_GET_FAIL"

// delete a product -- admin
export const  ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST"

export const  ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS"

export const  ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL"


// create new product -- admin
export const  CREATE_NEW_PRODUCT_REQUEST = "CREATE_NEW_PRODUCT_REQUEST"

export const  CREATE_NEW_PRODUCT_SUCCESS = "CREATE_NEW_PRODUCT_SUCCESS"

export const  CREATE_NEW_PRODUCT_FAIL = "CREATE_NEW_PRODUCT_FAIL"

// update product -- admin
export const  UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"

export const  UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"

export const  UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"


// reset success
export const RESET_SUCCESS = "RESET_SUCCESS"



export const CLEAR_ERROR = "CLEAR_ERROR"


