

// create/update product review
export const  CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"

export const  CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"

export const  CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL"


// get all rewiews of all products -- admin
export const  GET_ALL_REVIEWS_OF_ALL_PRODUCTS_REQUEST = "GET_ALL_REVIEWS_OF_ALL_PRODUCTS_REQUEST"

export const  GET_ALL_REVIEWS_OF_ALL_PRODUCTS_SUCCESS = "GET_ALL_REVIEWS_OF_ALL_PRODUCTS_SUCCESS"

export const  GET_ALL_REVIEWS_OF_ALL_PRODUCTS_FAIL = "GET_ALL_REVIEWS_OF_ALL_PRODUCTS_FAIL"


// get all rewiews of all products -- admin
export const  DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"

export const  DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"

export const  DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"



export const RESET_SUCCESS = "RESET_SUCCESS"

export const CLEAR_ERROR = "CLEAR_ERROR"