
// register new user
export const  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"

export const  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"

export const  USER_REGISTER_FAIL = "USER_REGISTER_FAIL"


// login user
export const  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"

export const  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const  USER_LOGIN_FAIL = "USER_LOGIN_FAIL"


// load user when user logged in
export const  USER_LOAD_REQUEST = "USER_LOAD_REQUEST"

export const  USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS"

export const  USER_LOAD_FAIL = "USER_LOAD_FAIL"


// user logout
export const  USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"

export const  USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"

export const  USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"


// update profile
export const  PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST"

export const  PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS"

export const  PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL"

export const  PROFILE_UPDATE_RESET = "PROFILE_UPDATE_RESET"


// update profile
export const  PASSWORD_UPDATE_REQUEST = "PASSWORD_UPDATE_REQUEST"

export const  PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS"

export const  PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL"

export const  PASSWORD_UPDATE_RESET = "PASSWORD_UPDATE_RESET"


// forgot password
export const  FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"

export const  FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"

export const  FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"


// reset password
export const  RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"

export const  RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"

export const  RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"


// get users list -- admin
export const  GET_USERS_LIST_REQUEST = "GET_USERS_LIST_REQUEST"

export const  GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS"

export const  GET_USERS_LIST_FAIL = "GET_USERS_LIST_FAIL"


// delete user -- admin
export const  DELETE_USER_REQUEST = "DELETE_USER_REQUEST"

export const  DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"

export const  DELETE_USER_FAIL = "DELETE_USER_FAIL"


// get single user -- admin
export const  GET_ADMIN_USER_REQUEST = "GET_ADMIN_USER_REQUEST"

export const  GET_ADMIN_USER_SUCCESS = "GET_ADMIN_USER_SUCCESS"

export const  GET_ADMIN_USER_FAIL = "GET_ADMIN_USER_FAIL"


// update user -- admin
export const  UPDATE_USER_ADMIN_REQUEST = "UPDATE_USER_ADMIN_REQUEST"

export const  UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS"

export const  UPDATE_USER_ADMIN_FAIL = "UPDATE_USER_ADMIN_FAIL"



export const RESET_SUCCESS = "RESET_SUCCESS"

export const CLEAR_ERROR = "CLEAR_ERROR"